version: "3"

services:
  node:
    build: .
    # image: node:alpine
    container_name: stock_market_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    # working_dir: /app
    volumes:
      - ./:/src
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${MYSQL_DB}
      SECRET: ${SECRET}
      PORT: ${PORT}

  db:
    container_name: stock_market_api_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

networks:
  default:
    name: api